module.exports = {
  up: function(migration, DataTypes) {
    migration.addColumn(
        'Calls',
        'CloneOrigineId',
        DataTypes.INTEGER
    );
    migration.addColumn(
        'CallTypes',
        'CloneOrigineId',
        DataTypes.INTEGER
    );
    migration.addColumn(
        'ParamValues',
        'CloneOrigineId',
        DataTypes.INTEGER
    );
    migration.addColumn(
        'Profils',
        'CloneOrigineId',
        DataTypes.INTEGER
    );
    migration.addColumn(
        'RelativeEvents',
        'CloneOrigineId',
        DataTypes.INTEGER
    );
    migration.addColumn(
        'RelativeTimelines',
        'CloneOrigineId',
        DataTypes.INTEGER
    );
    migration.addColumn(
        'SDIs',
        'CloneOrigineId',
        DataTypes.INTEGER
    );
    migration.addColumn(
        'ZoneContents',
        'CloneOrigineId',
        DataTypes.INTEGER
    );
    migration.addColumn(
        'Zones',
        'CloneOrigineId',
        DataTypes.INTEGER
    );
  },

  down: function(migration, DataTypes) {
    migration.removeColumn(
        'Calls',
        'CloneOrigineId'
    );
    migration.removeColumn(
        'CallTypes',
        'CloneOrigineId'
    );
    migration.removeColumn(
        'ParamValues',
        'CloneOrigineId'
    );
    migration.removeColumn(
        'Profils',
        'CloneOrigineId'
    );
    migration.removeColumn(
        'RelativeEvents',
        'CloneOrigineId'
    );
    migration.removeColumn(
        'RelativeTimelines',
        'CloneOrigineId'
    );
    migration.removeColumn(
        'SDI',
        'CloneOrigineId'
    );
    migration.removeColumn(
        'ZoneContents',
        'CloneOrigineId'
    );
    migration.removeColumn(
        'Zones',
        'CloneOrigineId'
    );
  }
};